#include <iostream>
#include <string>
#include <stdexcept>
using namespace std;
int main() {
    /*Программа делит число 10 на 0
    что приводит к ошибке деления на ноль. В случае ошибки
    программа выбрасывает исключение с сообщением "Division by zero!"
    которое затем выводится на экран.*/

    try {
        int x = 10;
        int y;
        cout << "Enter a number for delenie 10 na: ";
        cin >> y;

        if (y == 0) {
            throw "Division by zero!";
        }

        float result = x / y;
        cout << "Result: " << result << endl;
    }
    catch (const char* msg) {
        cerr << "Error: " << msg << endl;
    }

    cout << endl<< "_________________________________________________" << endl << endl << endl;

    //В примере ниже программа запрашивает у пользователя
    //ввод числа в виде строки, а затем пытается преобразовать
    //эту строку в целое число.Если введенное значение не
    //является корректным числом, программа обрабатывает
    //исключение и выводит сообщение об ошибке.



    try {
        string input;
        cout << "Enter a number: ";
        cin >> input;

        // Преобразование введенной строки в целое число
        int number = stoi (input);

        cout << "You entered: " << number << endl;
    }
    catch (const invalid_argument& e) {
        cerr << "Invalid argument: " << e.what() << endl;
    }
    catch (const std::out_of_range& e) {
        cerr << "Out of range: " << e.what() << endl;
    }
    catch (...) {
        cerr << "An error occurred while processing the input." << endl;
    }
    return 0;
}
